// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Web3    = require("web3");
var Web3Eth = require("web3-eth");

var inst = new Web3();

var ver = inst.version;

var g = new Web3Eth(/* `provider_url */[
      994922017,
      "Hello"
    ]);

exports.inst = inst;
exports.ver  = ver;
exports.g    = g;
/* inst Not a pure module */
